2024-03-24 12:24:59,346 INFO    MainThread:12104 [wandb_setup.py:_flush():76] Configure stats pid to 12104
2024-03-24 12:24:59,346 INFO    MainThread:12104 [wandb_setup.py:_flush():76] Loading settings from C:\Users\hugoa\.config\wandb\settings
2024-03-24 12:24:59,346 INFO    MainThread:12104 [wandb_setup.py:_flush():76] Loading settings from c:\Users\hugoa\H9\RL\GitHub Vrain\rl_levitation_control\rl_levitation_control\wandb\settings
2024-03-24 12:24:59,347 INFO    MainThread:12104 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-24 12:24:59,347 INFO    MainThread:12104 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-24 12:24:59,347 INFO    MainThread:12104 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-24 12:24:59,347 INFO    MainThread:12104 [wandb_init.py:_log_setup():506] Logging user logs to c:\Users\hugoa\H9\RL\GitHub Vrain\rl_levitation_control\rl_levitation_control\wandb\run-20240324_122459-nrqbll49\logs\debug.log
2024-03-24 12:24:59,348 INFO    MainThread:12104 [wandb_init.py:_log_setup():507] Logging internal logs to c:\Users\hugoa\H9\RL\GitHub Vrain\rl_levitation_control\rl_levitation_control\wandb\run-20240324_122459-nrqbll49\logs\debug-internal.log
2024-03-24 12:24:59,348 INFO    MainThread:12104 [wandb_init.py:init():546] calling init triggers
2024-03-24 12:24:59,348 INFO    MainThread:12104 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {}
2024-03-24 12:24:59,348 INFO    MainThread:12104 [wandb_init.py:init():568] re-initializing run, found existing run on stack: 8bpg2wzv
2024-03-24 12:24:59,349 INFO    MainThread:12104 [wandb_run.py:_finish():1854] finishing run hyperloopupv/5gdl/8bpg2wzv
2024-03-24 12:24:59,351 ERROR   MainThread:12104 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2024-03-24 12:24:59,351 INFO    MainThread:12104 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-24 12:24:59,351 INFO    MainThread:12104 [wandb_init.py:_jupyter_teardown():434] cleaning up jupyter logic
2024-03-24 12:24:59,351 INFO    MainThread:12104 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2024-03-24 12:24:59,352 INFO    MainThread:12104 [wandb_run.py:_restore():2066] restore
2024-03-24 12:24:59,352 INFO    MainThread:12104 [wandb_run.py:_restore():2072] restore done
2024-03-24 12:25:09,295 INFO    MainThread:12104 [wandb_run.py:_footer_history_summary_info():3422] rendering history
2024-03-24 12:25:09,295 INFO    MainThread:12104 [wandb_run.py:_footer_history_summary_info():3454] rendering summary
2024-03-24 12:25:09,298 INFO    MainThread:12104 [wandb_run.py:_footer_sync_info():3380] logging synced files
2024-03-24 12:25:09,302 INFO    MainThread:12104 [wandb_init.py:init():602] starting backend
2024-03-24 12:25:09,302 INFO    MainThread:12104 [wandb_init.py:init():606] setting up manager
2024-03-24 12:25:09,305 INFO    MainThread:12104 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2024-03-24 12:25:09,307 INFO    MainThread:12104 [wandb_init.py:init():613] backend started and connected
2024-03-24 12:25:09,309 INFO    MainThread:12104 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2024-03-24 12:25:09,309 INFO    MainThread:12104 [wandb_run.py:_label_probe_notebook():1214] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-03-24 12:25:09,309 INFO    MainThread:12104 [wandb_init.py:init():701] updated telemetry
2024-03-24 12:25:09,468 INFO    MainThread:12104 [wandb_init.py:init():741] communicating run to backend with 60.0 second timeout
2024-03-24 12:25:10,733 INFO    MainThread:12104 [wandb_run.py:_on_init():2133] communicating current version
2024-03-24 12:25:10,810 INFO    MainThread:12104 [wandb_run.py:_on_init():2142] got version response upgrade_message: "wandb version 0.16.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-03-24 12:25:10,810 INFO    MainThread:12104 [wandb_init.py:init():789] starting run threads in backend
2024-03-24 12:25:11,174 INFO    MainThread:12104 [wandb_run.py:_console_start():2114] atexit reg
2024-03-24 12:25:11,174 INFO    MainThread:12104 [wandb_run.py:_redirect():1969] redirect: SettingsConsole.WRAP_RAW
2024-03-24 12:25:11,174 INFO    MainThread:12104 [wandb_run.py:_redirect():2034] Wrapping output streams.
2024-03-24 12:25:11,174 INFO    MainThread:12104 [wandb_run.py:_redirect():2059] Redirects installed.
2024-03-24 12:25:11,175 INFO    MainThread:12104 [wandb_init.py:init():831] run started, returning control to user process
2024-03-24 12:26:03,868 INFO    MainThread:12104 [wandb_setup.py:_flush():76] Configure stats pid to 12104
2024-03-24 12:26:03,868 INFO    MainThread:12104 [wandb_setup.py:_flush():76] Loading settings from C:\Users\hugoa\.config\wandb\settings
2024-03-24 12:26:03,868 INFO    MainThread:12104 [wandb_setup.py:_flush():76] Loading settings from c:\Users\hugoa\H9\RL\GitHub Vrain\rl_levitation_control\rl_levitation_control\wandb\settings
2024-03-24 12:26:03,868 INFO    MainThread:12104 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-24 12:26:03,869 INFO    MainThread:12104 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-24 12:26:03,869 INFO    MainThread:12104 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-24 12:26:03,869 INFO    MainThread:12104 [wandb_init.py:_log_setup():506] Logging user logs to c:\Users\hugoa\H9\RL\GitHub Vrain\rl_levitation_control\rl_levitation_control\wandb\run-20240324_122603-ct4iwatb\logs\debug.log
2024-03-24 12:26:03,869 INFO    MainThread:12104 [wandb_init.py:_log_setup():507] Logging internal logs to c:\Users\hugoa\H9\RL\GitHub Vrain\rl_levitation_control\rl_levitation_control\wandb\run-20240324_122603-ct4iwatb\logs\debug-internal.log
2024-03-24 12:26:03,870 INFO    MainThread:12104 [wandb_init.py:_jupyter_setup():452] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000017CC5E8C4F0>
2024-03-24 12:26:03,870 INFO    MainThread:12104 [wandb_init.py:init():546] calling init triggers
2024-03-24 12:26:03,870 INFO    MainThread:12104 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {}
2024-03-24 12:26:03,870 INFO    MainThread:12104 [wandb_init.py:init():568] re-initializing run, found existing run on stack: nrqbll49
2024-03-24 12:26:03,871 INFO    MainThread:12104 [wandb_run.py:_finish():1854] finishing run hyperloopupv/5gdl/nrqbll49
2024-03-24 12:26:03,871 INFO    MainThread:12104 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2024-03-24 12:26:03,872 INFO    MainThread:12104 [wandb_run.py:_restore():2066] restore
2024-03-24 12:26:03,872 INFO    MainThread:12104 [wandb_run.py:_restore():2072] restore done
2024-03-24 12:26:07,806 INFO    MainThread:12104 [wandb_run.py:_footer_history_summary_info():3422] rendering history
2024-03-24 12:26:07,806 INFO    MainThread:12104 [wandb_run.py:_footer_history_summary_info():3454] rendering summary
2024-03-24 12:26:07,810 INFO    MainThread:12104 [wandb_run.py:_footer_sync_info():3380] logging synced files
