2023-12-05 19:13:25,836 INFO    MainThread:13340 [wandb_setup.py:_flush():76] Current SDK version is 0.16.0
2023-12-05 19:13:25,836 INFO    MainThread:13340 [wandb_setup.py:_flush():76] Configure stats pid to 13340
2023-12-05 19:13:25,836 INFO    MainThread:13340 [wandb_setup.py:_flush():76] Loading settings from C:\Users\hugoa\.config\wandb\settings
2023-12-05 19:13:25,836 INFO    MainThread:13340 [wandb_setup.py:_flush():76] Loading settings from c:\Users\hugoa\H9\RL\GitHub Vrain\rl_levitation_control\wandb\settings
2023-12-05 19:13:25,836 INFO    MainThread:13340 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-12-05 19:13:25,837 INFO    MainThread:13340 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-12-05 19:13:25,837 INFO    MainThread:13340 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-12-05 19:13:25,837 INFO    MainThread:13340 [wandb_init.py:_log_setup():524] Logging user logs to c:\Users\hugoa\H9\RL\GitHub Vrain\rl_levitation_control\wandb\run-20231205_191325-jy6qei5f\logs\debug.log
2023-12-05 19:13:25,837 INFO    MainThread:13340 [wandb_init.py:_log_setup():525] Logging internal logs to c:\Users\hugoa\H9\RL\GitHub Vrain\rl_levitation_control\wandb\run-20231205_191325-jy6qei5f\logs\debug-internal.log
2023-12-05 19:13:25,837 INFO    MainThread:13340 [wandb_init.py:init():564] calling init triggers
2023-12-05 19:13:25,838 INFO    MainThread:13340 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2023-12-05 19:13:25,838 INFO    MainThread:13340 [wandb_init.py:init():589] re-initializing run, found existing run on stack: kr38kufr
2023-12-05 19:13:25,839 INFO    MainThread:13340 [wandb_run.py:_finish():1962] finishing run hyperloopupv/1gdlcomplex/kr38kufr
2023-12-05 19:13:25,841 ERROR   MainThread:13340 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2023-12-05 19:13:25,841 INFO    MainThread:13340 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-12-05 19:13:25,841 INFO    MainThread:13340 [wandb_init.py:_jupyter_teardown():452] cleaning up jupyter logic
2023-12-05 19:13:25,841 INFO    MainThread:13340 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2023-12-05 19:13:25,841 INFO    MainThread:13340 [wandb_run.py:_restore():2185] restore
2023-12-05 19:13:25,842 INFO    MainThread:13340 [wandb_run.py:_restore():2191] restore done
2023-12-05 19:13:28,503 INFO    MainThread:13340 [wandb_run.py:_footer_history_summary_info():3760] rendering history
2023-12-05 19:13:28,503 INFO    MainThread:13340 [wandb_run.py:_footer_history_summary_info():3792] rendering summary
2023-12-05 19:13:28,507 INFO    MainThread:13340 [wandb_run.py:_footer_sync_info():3719] logging synced files
2023-12-05 19:13:28,639 INFO    MainThread:13340 [wandb_init.py:init():614] starting backend
2023-12-05 19:13:28,639 INFO    MainThread:13340 [wandb_init.py:init():618] setting up manager
2023-12-05 19:13:28,641 INFO    MainThread:13340 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2023-12-05 19:13:28,642 INFO    MainThread:13340 [wandb_init.py:init():624] backend started and connected
2023-12-05 19:13:28,647 INFO    MainThread:13340 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2023-12-05 19:13:28,647 INFO    MainThread:13340 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-12-05 19:13:28,647 INFO    MainThread:13340 [wandb_init.py:init():716] updated telemetry
2023-12-05 19:13:28,649 INFO    MainThread:13340 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2023-12-05 19:13:29,904 INFO    MainThread:13340 [wandb_run.py:_on_init():2254] communicating current version
2023-12-05 19:13:29,952 INFO    MainThread:13340 [wandb_run.py:_on_init():2263] got version response 
2023-12-05 19:13:29,952 INFO    MainThread:13340 [wandb_init.py:init():800] starting run threads in backend
2023-12-05 19:13:30,133 INFO    MainThread:13340 [wandb_run.py:_console_start():2233] atexit reg
2023-12-05 19:13:30,133 INFO    MainThread:13340 [wandb_run.py:_redirect():2088] redirect: wrap_raw
2023-12-05 19:13:30,133 INFO    MainThread:13340 [wandb_run.py:_redirect():2153] Wrapping output streams.
2023-12-05 19:13:30,134 INFO    MainThread:13340 [wandb_run.py:_redirect():2178] Redirects installed.
2023-12-05 19:13:30,134 INFO    MainThread:13340 [wandb_init.py:init():841] run started, returning control to user process
2023-12-05 19:17:52,316 INFO    MainThread:13340 [wandb_setup.py:_flush():76] Current SDK version is 0.16.0
2023-12-05 19:17:52,316 INFO    MainThread:13340 [wandb_setup.py:_flush():76] Configure stats pid to 13340
2023-12-05 19:17:52,316 INFO    MainThread:13340 [wandb_setup.py:_flush():76] Loading settings from C:\Users\hugoa\.config\wandb\settings
2023-12-05 19:17:52,317 INFO    MainThread:13340 [wandb_setup.py:_flush():76] Loading settings from c:\Users\hugoa\H9\RL\GitHub Vrain\rl_levitation_control\wandb\settings
2023-12-05 19:17:52,317 INFO    MainThread:13340 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-12-05 19:17:52,317 INFO    MainThread:13340 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-12-05 19:17:52,317 INFO    MainThread:13340 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-12-05 19:17:52,317 INFO    MainThread:13340 [wandb_init.py:_log_setup():524] Logging user logs to c:\Users\hugoa\H9\RL\GitHub Vrain\rl_levitation_control\wandb\run-20231205_191752-hgec5klq\logs\debug.log
2023-12-05 19:17:52,317 INFO    MainThread:13340 [wandb_init.py:_log_setup():525] Logging internal logs to c:\Users\hugoa\H9\RL\GitHub Vrain\rl_levitation_control\wandb\run-20231205_191752-hgec5klq\logs\debug-internal.log
2023-12-05 19:17:52,317 INFO    MainThread:13340 [wandb_init.py:_jupyter_setup():470] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002DD2D25EB20>
2023-12-05 19:17:52,318 INFO    MainThread:13340 [wandb_init.py:init():564] calling init triggers
2023-12-05 19:17:52,318 INFO    MainThread:13340 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2023-12-05 19:17:52,318 INFO    MainThread:13340 [wandb_init.py:init():589] re-initializing run, found existing run on stack: jy6qei5f
2023-12-05 19:17:52,320 INFO    MainThread:13340 [wandb_run.py:_finish():1962] finishing run hyperloopupv/1gdlcomplex/jy6qei5f
2023-12-05 19:17:52,320 INFO    MainThread:13340 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2023-12-05 19:17:52,321 INFO    MainThread:13340 [wandb_run.py:_restore():2185] restore
2023-12-05 19:17:52,321 INFO    MainThread:13340 [wandb_run.py:_restore():2191] restore done
2023-12-05 19:17:57,511 INFO    MainThread:13340 [wandb_run.py:_footer_history_summary_info():3760] rendering history
2023-12-05 19:17:57,511 INFO    MainThread:13340 [wandb_run.py:_footer_history_summary_info():3792] rendering summary
2023-12-05 19:17:57,514 INFO    MainThread:13340 [wandb_run.py:_footer_sync_info():3719] logging synced files
